### ISSUE TITLE
Card doesn't support new weather entitles without forecast attributes

### ISSUE THREAD

**Issue by Scoop2389** [Makin-Things/platinum-weather-card#101]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
Card Version: 1.0.5
Home Assistant Core: 2023.9

**Last working release (if known):**
Card Version: 1.0.5
Home Assistant Core: 2023.8.4

**Browser and Operating System:**
Windows, Edge, Chrome + Android, Home Assistant Mobile App

**Description of problem:**
In Home Assistant Core 2023.9, a new weather forecast scheme was introduced in which entities no longer have forecast attributes, and instead forecast data must be retrieved by calling a service (weather.get_forecast) ([Ref](https://www.home-assistant.io/blog/2023/09/06/release-20239/#weather-forecast-service)). This card does not call the service, and therefore entites without forecast attributes do not appear in this card.

**Javascript errors shown in the web inspector (if applicable):**
```
platinum-weather-card-df6d26e2.js:41  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'filter')
    at ge._getForecastPropFromWeather (platinum-weather-card-df6d26e2.js:268:71)
    at ge._checkForErrors (platinum-weather-card-df6d26e2.js:73:17788)
    at ge.render (platinum-weather-card-df6d26e2.js:268:1014)
    at ge.update (platinum-weather-card-df6d26e2.js:47:547)
    at ge.performUpdate (platinum-weather-card-df6d26e2.js:41:5079)
    at ge.scheduleUpdate (platinum-weather-card-df6d26e2.js:41:4726)
    at ge._$EC (platinum-weather-card-df6d26e2.js:41:4634)
```

**Comment by Scoop2389** [comment]
I am suggesting removal of if this card from HACS because it has not been maintained since 2022. You can vote and comment on it here: https://github.com/hacs/integration/issues/3290

**Comment by Makin-Things** [comment]
@Scoop2389 , considering it is open source software and you have not contributed or funded my work in any way whatsoever I really cant fathom how you think this behaviour in any way is appropriate. The HA guys randomly change things that break work done by individuals to try and make life better by filling the gaps. I am happy if it it gets removed from HACS because then I won't have to deal with ungrateful people like yourself. Bottom line, if you don't like it don't use it and stuff your whinging.

**Comment by rudizl** [comment]
> @Scoop2389 , considering it is open source software and you have not contributed or funded my work in any way whatsoever I really cant fathom how you think this behaviour in any way is appropriate. The HA guys randomly change things that break work done by individuals to try and make life better by filling the gaps. I am happy if it it gets removed from HACS because then I won't have to deal with ungrateful people like yourself. Bottom line, if you don't like it don't use it and stuff your whinging. Also you broke my number 1 rule. If you want any help , don't be a dick.

@Makin-Things , do you have plans to update the card? I`m using PWS and this card is the only one that can show what I want :(

**Comment by Scoop2389** [comment]
I was not trying to be mean or aggressive in any way. The readme of your card even says that it is not maintained. Unmaintained cards should not be part of HACS default repositories. You also have many open pull requests that it seems you have not reviewed. If you do wish to look over the pull requests and/or start maintaining the card again, I will happily close the HACS issue.

**Comment by Sudo-Rob** [comment]
@Scoop2389,

This weather card still works for me, and could potentially work for you if you can generate entities from PWS (which, if I'm not mistaken, appears to be an unsupported integration).  If you don't already use it, making sensor templates is a useful skill to learn.  Moreover, there's a reasonable chance someone will come up with a template or another way to use this card before the transition to the new scheme occurs.

Removing this integration because it doesn't comply with your needs may be a disservice to others, not to mention its creator, or even yourself.  Just because you can do something doesn't necessarily mean you should.

Just sayin'.

Respectfully.

**Comment by Scoop2389** [comment]
This is the type of reasonable discussion that makes me want to contribute and help resolve an issue like this. Thank you.

If you don't mind me asking, what weather forecast integration do you use? I have been trying to find one that works with this card (or any other similar weather card), but I haven't yet.

**Comment by Sudo-Rob** [comment]
This is not the venue for support.  

Start here:  https://community.home-assistant.io/t/platinum-weather-card-support/449166

**Comment by DavidFW1960** [comment]
> (I closed the HACS request)

I don't think you get how arrogant and disrespectful opening issues like this is and is perceived by the community.

**Comment by Scoop2389** [comment]
I'm sorry, I wasn't ever trying to be mean or arrogant. I was trying to do the right thing to prevent people from having to deal with things that are broken.
